"""
Notion integration for Project Incubator MCP Server

Handles sync with Notion databases:
- Quick Capture: Quick captures during ideation
- Projects: Project metadata and status (optional)
- Session Log: Session tracking for continuity (optional)

Expected Notion schema for Quick Capture database:
- Capture (title) - The idea text
- Type (select) - Options: 💡 Idea, 🐛 Issue, ✨ Feature, ❓ Question, 📝 Note
- Created (created_time) - Auto-generated by Notion
- Processed (checkbox) - For workflow tracking
"""

import os
from datetime import datetime
from typing import Optional
from notion_client import Client
from notion_client.errors import APIResponseError


# Map Incubator capture types to Notion type options
CAPTURE_TYPE_MAP = {
    "Research Question": "❓ Question",
    "Resource": "📝 Note",
    "Connection": "💡 Idea",
    "Follow-up": "✨ Feature",
    "Random": "💡 Idea",
    # Also support direct Notion types
    "💡 Idea": "💡 Idea",
    "🐛 Issue": "🐛 Issue",
    "✨ Feature": "✨ Feature",
    "❓ Question": "❓ Question",
    "📝 Note": "📝 Note",
}


class NotionSync:
    """Handles all Notion API interactions"""

    def __init__(self):
        self.api_key = os.environ.get("NOTION_API_KEY")
        self.ideas_db_id = os.environ.get("NOTION_IDEAS_DB_ID")
        self.projects_db_id = os.environ.get("NOTION_PROJECTS_DB_ID")
        self.sessions_db_id = os.environ.get("NOTION_SESSIONS_DB_ID")

        self._client = None
        self._initialized = False
        self._init_error = None

    @property
    def client(self) -> Optional[Client]:
        """Lazy initialization of Notion client"""
        if self._client is None and self.api_key:
            try:
                self._client = Client(auth=self.api_key)
                self._initialized = True
            except Exception as e:
                self._init_error = str(e)
        return self._client

    @property
    def is_configured(self) -> bool:
        """Check if Notion is properly configured"""
        return bool(self.api_key and self.ideas_db_id)

    def get_status(self) -> dict:
        """Get Notion connection status"""
        return {
            "configured": self.is_configured,
            "api_key_set": bool(self.api_key),
            "ideas_db_set": bool(self.ideas_db_id),
            "ideas_db_id": self.ideas_db_id,
            "projects_db_set": bool(self.projects_db_id),
            "sessions_db_set": bool(self.sessions_db_id),
            "initialized": self._initialized,
            "error": self._init_error,
            "type_mapping": CAPTURE_TYPE_MAP,
        }

    def create_capture(self, capture: dict) -> dict:
        """
        Create a new capture in the Quick Capture database.

        Args:
            capture: Dict with keys: idea, type, captured_at, phase, project

        Returns:
            Dict with notion_id if successful, error otherwise
        """
        if not self.is_configured:
            return {"error": "Notion not configured", "synced": False}

        if not self.client:
            return {"error": self._init_error or "Failed to initialize Notion client", "synced": False}

        try:
            # Map capture type to Notion type
            capture_type = capture.get("type", "Random")
            notion_type = CAPTURE_TYPE_MAP.get(capture_type, "💡 Idea")

            # Get the idea text
            idea_text = capture["idea"]

            # Build properties for the page
            properties = {
                "Capture": {
                    "title": [{"text": {"content": idea_text[:2000]}}]  # Notion title limit
                },
                "Type": {
                    "select": {"name": notion_type}
                },
                "Processed": {
                    "checkbox": False
                },
            }

            # Create the page
            response = self.client.pages.create(
                parent={"database_id": self.ideas_db_id},
                properties=properties
            )

            return {
                "notion_id": response["id"],
                "url": response.get("url"),
                "synced": True,
                "mapped_type": notion_type,
                "original_type": capture_type,
            }

        except APIResponseError as e:
            return {"error": f"Notion API error: {e.message}", "synced": False}
        except Exception as e:
            return {"error": f"Sync failed: {str(e)}", "synced": False}

    def sync_captures(self, captures: list) -> dict:
        """
        Sync multiple captures to Notion.

        Args:
            captures: List of capture dicts

        Returns:
            Summary of sync results
        """
        if not captures:
            return {"synced": 0, "failed": 0, "errors": []}

        if not self.is_configured:
            return {
                "synced": 0,
                "failed": len(captures),
                "errors": ["Notion not configured"]
            }

        results = {"synced": 0, "failed": 0, "errors": [], "notion_ids": []}

        for capture in captures:
            result = self.create_capture(capture)
            if result.get("synced"):
                results["synced"] += 1
                results["notion_ids"].append(result.get("notion_id"))
            else:
                results["failed"] += 1
                results["errors"].append(result.get("error"))

        return results

    def get_unprocessed_captures(self, limit: int = 10) -> list:
        """
        Get unprocessed captures from Notion.

        Returns:
            List of capture dicts
        """
        if not self.is_configured or not self.client:
            return []

        try:
            response = self.client.databases.query(
                database_id=self.ideas_db_id,
                filter={
                    "property": "Processed",
                    "checkbox": {"equals": False}
                },
                sorts=[{"timestamp": "created_time", "direction": "descending"}],
                page_size=limit
            )

            captures = []
            for page in response.get("results", []):
                props = page.get("properties", {})
                captures.append({
                    "notion_id": page["id"],
                    "idea": self._get_title(props.get("Capture", {})),
                    "type": self._get_select(props.get("Type", {})),
                    "created_at": page.get("created_time", ""),
                })

            return captures

        except Exception:
            return []

    def log_session(self, session_data: dict) -> dict:
        """
        Log a session to the Session Log database.

        Args:
            session_data: Dict with summary, action_items, etc.

        Returns:
            Result dict
        """
        if not self.sessions_db_id or not self.client:
            return {"logged": False, "error": "Sessions database not configured"}

        try:
            properties = {
                "Session": {
                    "title": [{"text": {"content": session_data.get("title", f"Session {datetime.now().strftime('%Y-%m-%d %H:%M')}")}}]
                },
                "Date": {
                    "date": {"start": datetime.now().isoformat()}
                },
                "Summary": {
                    "rich_text": [{"text": {"content": session_data.get("summary", "")[:2000]}}]
                },
            }

            if session_data.get("action_items"):
                properties["Action Items"] = {
                    "rich_text": [{"text": {"content": session_data["action_items"][:2000]}}]
                }

            response = self.client.pages.create(
                parent={"database_id": self.sessions_db_id},
                properties=properties
            )

            return {"logged": True, "notion_id": response["id"]}

        except Exception as e:
            return {"logged": False, "error": str(e)}

    def find_project(self, project_name: str) -> Optional[dict]:
        """
        Find a project by name in the Projects database.

        Returns:
            Project dict or None
        """
        if not self.projects_db_id or not self.client:
            return None

        try:
            response = self.client.databases.query(
                database_id=self.projects_db_id,
                filter={
                    "property": "Name",
                    "title": {"equals": project_name}
                },
                page_size=1
            )

            if response.get("results"):
                page = response["results"][0]
                props = page.get("properties", {})
                return {
                    "notion_id": page["id"],
                    "name": self._get_title(props.get("Name", {})),
                    "status": self._get_select(props.get("Status", {})),
                    "description": self._get_rich_text(props.get("Description", {})),
                }

            return None

        except Exception:
            return None

    # --- Helper methods for extracting Notion property values ---

    def _get_title(self, prop: dict) -> str:
        """Extract title text from Notion property"""
        title_list = prop.get("title", [])
        if title_list:
            return title_list[0].get("text", {}).get("content", "")
        return ""

    def _get_select(self, prop: dict) -> str:
        """Extract select value from Notion property"""
        select = prop.get("select")
        if select:
            return select.get("name", "")
        return ""

    def _get_date(self, prop: dict) -> str:
        """Extract date from Notion property"""
        date = prop.get("date")
        if date:
            return date.get("start", "")
        return ""

    def _get_rich_text(self, prop: dict) -> str:
        """Extract rich text from Notion property"""
        rich_text = prop.get("rich_text", [])
        if rich_text:
            return rich_text[0].get("text", {}).get("content", "")
        return ""


# Singleton instance
notion = NotionSync()
